# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: jacopen@gmail.com
brand: showKs
headline: aaaaaaaaaaaaaaaaaaaaaa
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 630367

# Contacts
email: your.name@gmail.com
phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

